## Movie Data Collection - Part 1 
### Course Advanced Data Mining and Analysis in Python  

**Team:**  
Miriam Dinay 212296099  
Hila Halberstadt 032540668

**GitHub:**  
https://github.com/MiriamDinay/Movie-Data-Collection-Project1

#### Uploading IMDb Tables, Data Cleaning, Filtering, and Loading

In [1]:
import pandas as pd

In [2]:
# df_movies = pd.read_csv('title.basics.tsv', sep='\t', nrows=10)
# df_movies

In [3]:
df_movies = pd.read_csv('title.basics.tsv', sep='\t')
df_movies.head(10)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short
5,tt0000006,short,Chinese Opium Den,Chinese Opium Den,0,1894,\N,1,Short
6,tt0000007,short,Corbett and Courtney Before the Kinetograph,Corbett and Courtney Before the Kinetograph,0,1894,\N,1,"Short,Sport"
7,tt0000008,short,Edison Kinetoscopic Record of a Sneeze,Edison Kinetoscopic Record of a Sneeze,0,1894,\N,1,"Documentary,Short"
8,tt0000009,movie,Miss Jerry,Miss Jerry,0,1894,\N,45,Romance
9,tt0000010,short,Leaving the Factory,La sortie de l'usine Lumière à Lyon,0,1895,\N,1,"Documentary,Short"

In [4]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12455708 entries, 0 to 12455707
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          object
 1   titleType       object
 2   primaryTitle    object
 3   originalTitle   object
 4   isAdult         int64
 5   startYear       object
 6   endYear         object
 7   runtimeMinutes  object
 8   genres          object
dtypes: int64(1), object(8)
memory usage: 855.3+ MB

In [5]:
df_movies['startYear'] = pd.to_numeric(df_movies['startYear'], errors='coerce')
df_movies['runtimeMinutes'] = pd.to_numeric(df_movies['runtimeMinutes'], errors='coerce')

In [6]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12455708 entries, 0 to 12455707
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          object
 1   titleType       object
 2   primaryTitle    object
 3   originalTitle   object
 4   isAdult         int64
 5   startYear       float64
 6   endYear         object
 7   runtimeMinutes  float64
 8   genres          object
dtypes: float64(2), int64(1), object(6)
memory usage: 855.3+ MB

In [7]:
#סינון שנת יציאת הסרט, זמן והאות שקיבלנו לפי הדרישות במטלה
filtered_movies_df = df_movies[(df_movies['titleType'] == 'movie') & (df_movies['startYear'] <= 2024) & 
(df_movies['runtimeMinutes'] >= 60) & (df_movies['runtimeMinutes'] <= 300) & (df_movies['primaryTitle'].str.startswith(('L', 'l'), na=False))].copy()

filtered_movies_df

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
1739,tt0001756,movie,Lucha por la herencia,Lucha por la herencia,0,1911.0,\N,92.0,\N
1773,tt0001790,movie,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,0,1913.0,\N,60.0,Drama
3047,tt0003076,movie,Livets konflikter,Livets konflikter,0,1913.0,\N,64.0,Drama
3073,tt0003102,movie,Love Everlasting,Ma l'amor mio non muore...,0,1914.0,\N,90.0,Drama
3130,tt0003159,movie,"Les Misérables, Part 2: Fantine",Les misérables - Époque 2: Fantine,0,1913.0,\N,300.0,Drama
...,...,...,...,...,...,...,...,...,...
12449230,tt9902832,movie,Lila Kourkoulakou,Lila Kourkoulakou,0,2017.0,\N,60.0,"Biography,Documentary"
12449772,tt9904014,movie,Lost in Klessin,Lost in Klessin,0,2018.0,\N,90.0,War
12450734,tt9906128,movie,Leak (Penangkeb),Leak (Penangkeb),0,2019.0,\N,75.0,Horror
12451822,tt9908390,movie,Le lion,Le lion,0,2020.0,\N,95.0,Comedy
12454850,tt9914942,movie,Life Without Sara Amat,La vida sense la Sara Amat,0,2019.0,\N,74.0,Drama

#### Adding columns from Ratings table

In [8]:
df_ratings = pd.read_csv('title.ratings.tsv', sep='\t')
df_ratings.columns

Index(['tconst', 'averageRating', 'numVotes'], dtype='object')

In [9]:
final_df = filtered_movies_df.merge(df_ratings, on='tconst', how='left')
final_df.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
0,tt0001756,movie,Lucha por la herencia,Lucha por la herencia,0,1911.0,\N,92.0,\N,4.8,9.0
1,tt0001790,movie,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,0,1913.0,\N,60.0,Drama,5.9,69.0
2,tt0003076,movie,Livets konflikter,Livets konflikter,0,1913.0,\N,64.0,Drama,NaN,NaN
3,tt0003102,movie,Love Everlasting,Ma l'amor mio non muore...,0,1914.0,\N,90.0,Drama,6.1,182.0
4,tt0003159,movie,"Les Misérables, Part 2: Fantine",Les misérables - Époque 2: Fantine,0,1913.0,\N,300.0,Drama,5.7,66.0

#### Adding columns from the Principals table (actors)

In [10]:
df_principals_try = pd.read_csv('title.principals.tsv', sep='\t',nrows=5)
df_principals_try

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0005690,producer,producer,\N
3,tt0000001,4,nm0374658,cinematographer,director of photography,\N
4,tt0000002,1,nm0721526,director,\N,\N

In [11]:
valid_tconsts = final_df['tconst'].unique() #מכינות רשימה של הסרטים שיש לנו (כדי לסנן לפיה)
chunks = []

for chunk in pd.read_csv('title.principals.tsv', sep='\t', usecols=['tconst', 'nconst', 'category'], chunksize=200000): #קראנו בחלקים עקב דאתא מאד כבד
    filtered = chunk[(chunk['category'].isin(['actor', 'actress'])) & (chunk['tconst'].isin(valid_tconsts))]
    chunks.append(filtered)

df_actors = pd.concat(chunks)
print(f"נטענו {len(df_actors)} שורות של שחקנים ושחקניות רלוונטיים.")
df_actors.head()

נטענו 158426 שורות של שחקנים ושחקניות רלוונטיים.

          tconst     nconst category
10121  tt0001756  nm0034454    actor
10122  tt0001756  nm0034548    actor
10123  tt0001756  nm0679170    actor
10124  tt0001756  nm0688764  actress
10125  tt0001756  nm0764534    actor

In [12]:
top_5_actors = df_actors.groupby('tconst').head(5)
actors_grouped = top_5_actors.groupby('tconst')['nconst'].apply(list).reset_index()
actors_grouped.rename(columns={'nconst': 'lead_actors_ids'}, inplace=True)

print("מוכן למיזוג")

מוכן למיזוג

In [13]:
final_df = final_df.merge(actors_grouped, on='tconst', how='left')
final_df.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,lead_actors_ids
0,tt0001756,movie,Lucha por la herencia,Lucha por la herencia,0,1911.0,\N,92.0,\N,4.8,9.0,"[nm0034454, nm0034548, nm0679170, nm0688764, n..."
1,tt0001790,movie,"Les Misérables, Part 1: Jean Valjean",Les misérables - Époque 1: Jean Valjean,0,1913.0,\N,60.0,Drama,5.9,69.0,"[nm0470307, nm0959921, nm0893346, nm0592965, n..."
2,tt0003076,movie,Livets konflikter,Livets konflikter,0,1913.0,\N,64.0,Drama,NaN,NaN,"[nm0014363, nm0874799, nm0526234, nm0679453, n..."
3,tt0003102,movie,Love Everlasting,Ma l'amor mio non muore...,0,1914.0,\N,90.0,Drama,6.1,182.0,"[nm0096330, nm0094801, nm0743102, nm0744105, n..."
4,tt0003159,movie,"Les Misérables, Part 2: Fantine",Les misérables - Époque 2: Fantine,0,1913.0,\N,300.0,Drama,5.7,66.0,"[nm0893346, nm0296344, nm0592965, nm0470307, n..."

In [14]:
len(final_df)

22427

In [15]:
final_columns = ['tconst','primaryTitle','startYear', 'genres', 'runtimeMinutes', 'averageRating', 'numVotes', 'lead_actors_ids']
final_df = final_df[final_columns].copy()

print(final_df.columns)
final_df.head()

Index(['tconst', 'primaryTitle', 'startYear', 'genres', 'runtimeMinutes',
       'averageRating', 'numVotes', 'lead_actors_ids'],
      dtype='object')

,tconst,primaryTitle,startYear,genres,runtimeMinutes,averageRating,numVotes,lead_actors_ids
0,tt0001756,Lucha por la herencia,1911.0,\N,92.0,4.8,9.0,"[nm0034454, nm0034548, nm0679170, nm0688764, n..."
1,tt0001790,"Les Misérables, Part 1: Jean Valjean",1913.0,Drama,60.0,5.9,69.0,"[nm0470307, nm0959921, nm0893346, nm0592965, n..."
2,tt0003076,Livets konflikter,1913.0,Drama,64.0,NaN,NaN,"[nm0014363, nm0874799, nm0526234, nm0679453, n..."
3,tt0003102,Love Everlasting,1914.0,Drama,90.0,6.1,182.0,"[nm0096330, nm0094801, nm0743102, nm0744105, n..."
4,tt0003159,"Les Misérables, Part 2: Fantine",1913.0,Drama,300.0,5.7,66.0,"[nm0893346, nm0296344, nm0592965, nm0470307, n..."

#### Selecting 5,000 rows

Instead of selecting 5,000 rows randomly, we chose the 5,000 rows that have complete data in all columns and a high probability of having data available when scraping Wikipedia.

In [16]:
non_null_cols = ['primaryTitle', 'startYear','genres', 'runtimeMinutes', 'averageRating', 'numVotes', 'lead_actors_ids']
df_filtered = final_df.dropna(subset=non_null_cols).copy()
final_df = df_filtered.sort_values(by='numVotes', ascending=False).head(5000).copy()

#מחקנו אין צורך שזה ישמר בזכרון
del df_filtered 
import gc
gc.collect()

print(final_df.shape)

(5000, 8)

In [17]:
final_df['startYear'] = final_df['startYear'].astype(int)
final_df['runtimeMinutes'] = final_df['runtimeMinutes'].astype(int)
final_df['numVotes'] = final_df['numVotes'].astype(int)

final_df[['primaryTitle', 'startYear', 'runtimeMinutes', 'numVotes']].head()

                 primaryTitle  startYear  runtimeMinutes  numVotes
3842   Léon: The Professional       1994             110   1348971
18011                   Logan       2017             137    924570
4056        Life Is Beautiful       1997             116    811399
18796              La La Land       2016             128    760490
9293               Life of Pi       2012             127    699443

In [18]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 3842 to 8451
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tconst           5000 non-null   object
 1   primaryTitle     5000 non-null   object
 2   startYear        5000 non-null   int64
 3   genres           5000 non-null   object
 4   runtimeMinutes   5000 non-null   int64
 5   averageRating    5000 non-null   float64
 6   numVotes         5000 non-null   int64
 7   lead_actors_ids  5000 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 351.6+ KB

#### HTML Files + Web Scraping from Wikipedia

In [19]:
!pip install CurrencyConverter

Requirement already satisfied: CurrencyConverter in c:\users\user\anaconda3\lib\site-packages (0.18.17)

In [20]:
import os #עבור שמירת תקייה במחשב
import requests
import time
import re
from bs4 import BeautifulSoup
from tqdm import tqdm #מד התקדמות של ההרצה
from datetime import date
from currency_converter import CurrencyConverter

In [21]:
c = CurrencyConverter(fallback_on_missing_rate=True) #משתנה להמרת מטבעות (הגדרנו שיאפשר להמיר גם אם חסר התאריך המדויק)

# יצירת תיקייה לשמירת דפי ויקיפדיה אצלנו במחשב כדי לחסוך זמן הורדה
if not os.path.exists('wiki_pages'):
    os.makedirs('wiki_pages')

# בנינו מילון של מטבעות נפוצים בויקיפדיה
CURRENCY_MAP = {
    '£': 'GBP', 'pound': 'GBP',
    'lit.': 'ITL', 'lire': 'ITL',
    '€': 'EUR', 'euro': 'EUR',
    '¥': 'JPY', 'yen': 'JPY',
    '₹': 'INR', 'rupee': 'INR',
    'francs': 'FRF', 'franc': 'FRF'
}

In [22]:
# פונקציה שמקבלת את הטקסט של התקציב מויקיפדיה ואת שנת היציאה של הסרט
import re
from datetime import date

def parse_wiki_money(text, year):
    if not text or pd.isna(text): 
        return None
        
    lines = str(text).split('\n')
    clean_lines = []
    for line in lines:
        if any(word in line.lower() for word in ['tickets', 'admission', 'כרטיסים']):
            continue
        clean_lines.append(line)
    
    filtered_text = " ".join(clean_lines)
    text_clean = re.sub(r'\[.*?\]', '', filtered_text)

    usd_in_parens = re.findall(r'\(\s*\$\s*([\d,\.]+)\s*(?:million|billion)?\s*\)', text_clean, re.IGNORECASE)
    if usd_in_parens:
        val = float(usd_in_parens[0].replace(',', ''))
        if 'billion' in text_clean.split('(')[1].split(')')[0].lower():
            val *= 1000
        return round(val, 2)

    text_lower = text_clean.lower()
    currency = 'USD'
    if '$' not in text_clean and 'usd' not in text_lower:
        currency = None
        best_pos = len(text_lower)
        for key, iso in CURRENCY_MAP.items():
            pos = text_lower.find(key)
            if pos != -1 and pos < best_pos:
                best_pos = pos
                currency = iso
        if not currency: return None

    text_prep = text_clean.replace(',', '').replace('—', '-').replace('–', '-')
    numbers = re.findall(r'(\d+\.?\d*)', text_prep)
    if not numbers: return None

    multiplier = 1000 if 'billion' in text_lower else 1
    

    vals = [float(n) * multiplier for n in numbers if float(n) < 1000000]
    if not vals: return None
    avg_orig = sum(vals) / len(vals)

    if currency != 'USD':
        try:
            res = c.convert(avg_orig, currency, 'USD', date=date(int(year), 1, 1)) #המרה לפי שנת היציאה של הסרט
        except:
            try: res = c.convert(avg_orig, currency, 'USD') #אבל אם הסרט ישן אז שימיר לפי שער ההמרה העדכני
            except: return None
    else:
        res = avg_orig

    return round(res, 2)

In [23]:
#פונקציה ששומרת את הדפים של הHTML במחשב
def get_movie_html_with_cache(tconst, title, year):
    file_path = f'wiki_pages/{tconst}.html'
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            return f.read(), "Cached", "Local File"

    # אופציות אפשריות לURL של דפי ויקיפדיה
    formatted_title = str(title).replace(' ', '_')
    urls_to_try = [
        f"https://en.wikipedia.org/wiki/{formatted_title}_({year}_film)",
        f"https://en.wikipedia.org/wiki/{formatted_title}_({year}_American_film)", #אופציות נוספות שנתקלנו בהן בבדיקות אז הוספנו
        f"https://en.wikipedia.org/wiki/{formatted_title}_({year}_British_film)",  
        f"https://en.wikipedia.org/wiki/{formatted_title}_(film)",
        f"https://en.wikipedia.org/wiki/{formatted_title}"
    ]

    for url in urls_to_try:
        try:
            headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'}
            response = requests.get(url, headers=headers, timeout=10)
            
            if response.status_code == 200 and 'infobox' in response.text.lower():
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(response.text)
                time.sleep(0.5) 
                return response.text, "Success", url
        except:
            continue
            
    return None, "Not Found", None

In [24]:
#פונקציה לחילוץ הנתונים הנדרשים מדף הויקיפדיה
def extract_movie_data(html_content, year):
    info = {'Language': None, 'Country': None, 'budget': None, 'BoxOffice': None, 'plot': None}
    if not html_content: 
        return info
        
    soup = BeautifulSoup(html_content, 'html.parser')
    infobox = soup.find("table", {"class": "infobox vevent"})
    if infobox:
        for row in infobox.find_all("tr"):
            header = row.find("th")
            value = row.find("td")
            
            if header and value:
                label = header.get_text().lower().strip()
                
                for sup in value.find_all(['sup', 'style']):
                    sup.decompose()
                items = [text.strip() for text in value.stripped_strings if text.strip()]
                
                if len(items) == 1:
                    val_data = items[0]
                elif len(items) > 1:
                    val_data = items
                else:
                    val_data = None
                
                if 'language' in label: 
                    info['Language'] = val_data
                elif 'country' in label or 'countries' in label: 
                    info['Country'] = val_data
                elif 'budget' in label: 
                    info['budget'] = parse_wiki_money(value.get_text(), year)
                elif 'box office' in label:
                    info['BoxOffice'] = parse_wiki_money(value.get_text(), year)

    # חילוץ הplot
    all_headers = soup.find_all(['h2', 'h3'])
    plot_header = None
    for header in all_headers:
        text = header.get_text().lower()
        if 'plot' in text or 'synopsis' in text or 'summary' in text:
            plot_header = header
            break
            
    if plot_header:
        plot_paragraphs = []
        for element in plot_header.find_all_next():
            if element.name in ['h2', 'h3']:
                break
            if element.name == 'p':
                p_text = element.get_text().strip()
                if p_text:
                    plot_paragraphs.append(p_text)
                    
        full_plot = " ".join(plot_paragraphs)
        full_plot = re.sub(r'\[\d+\]', '', full_plot)
        
        if full_plot.strip():
            info['plot'] = full_plot
        else:
            info['plot'] = "Plot description missing"
            
    return info

In [25]:
final_results = []

# השתמשנו בtqdm כדי לראות ויזואלית את קצב ההתקדמות שלנו
for index, row in tqdm(final_df.iterrows(), total=len(final_df)):
    html, status, final_url = get_movie_html_with_cache(row['tconst'], row['primaryTitle'], row['startYear'])
    movie_info = extract_movie_data(html, row['startYear'])
    full_row = {**row.to_dict(), **movie_info, 'wiki_url': final_url, 'wiki_status': status} # איחוד הנתונים
    final_results.append(full_row)

    # גיבוי לייתר ביטחון
    if len(final_results) % 100 == 0:
        pd.DataFrame(final_results).to_csv('dataset_backup.csv', index=False)

dataset_df = pd.DataFrame(final_results)

100%|██████████| 5000/5000 [35:15<00:00,  2.36it/s]

In [26]:
columns = ['tconst', 'primaryTitle', 'startYear', 'genres', 'lead_actors_ids',
    'runtimeMinutes', 'averageRating', 'Language', 'Country', 'numVotes','budget', 'BoxOffice', 'plot']

final_output_df = dataset_df[columns].copy()
final_output_df.to_csv('dataset.csv', index=False)

In [27]:
final_output_df.head(5)

,tconst,primaryTitle,startYear,genres,lead_actors_ids,runtimeMinutes,averageRating,Language,Country,numVotes,budget,BoxOffice,plot
0,tt0110413,Léon: The Professional,1994,"Action,Crime,Drama","[nm0000606, nm0000198, nm0000204, nm0000732, n...",110,8.5,English,France,1348971,16.0,19.5,"Léon is an Italian-American hitman (or ""cleane..."
1,tt3315342,Logan,2017,"Action,Drama,Sci-Fi","[nm0413168, nm0413168, nm0001772, nm6748436, n...",137,8.1,English,United States,924570,112.0,619.2,"In 2029, no mutants have been born in 25 years..."
2,tt0118799,Life Is Beautiful,1997,"Comedy,Drama,Romance","[nm0000905, nm0000971, nm0134493, nm0243842, n...",116,8.6,Italian,Italy,811399,NaN,230.1,"In 1939, in Fascist Italy, young Italian Jew G..."
3,tt3783958,La La Land,2016,"Comedy,Drama,Music","[nm0331516, nm1297015, nm1679669, nm0799777, n...",128,8.0,English,United States,760490,30.0,504.6,"While stuck in Los Angeles traffic (""Another D..."
4,tt0454876,Life of Pi,2012,"Adventure,Drama,Fantasy","[nm4139037, nm0451234, nm1300009, nm0007102, n...",127,7.9,English,"[United States, United Kingdom, Taiwan]",699443,120.0,609.0,"In Montreal, Canada, a writer meets Pi Patel, ..."

In [28]:
# #בדיקות שלנו לבדוק מטבעות וכו
# final_output_df[final_output_df["Language"] != "English"].head(20)
# # len(final_output_df[final_output_df["Language"] != "English"])

In [29]:
# בדיקות
print(final_output_df.iloc[4]['primaryTitle'] + ":")
print("-" * 30)
print(final_output_df.iloc[4]['plot'])
print(final_output_df.iloc[4]['Country'])
print(final_output_df.iloc[4]['Language'])

Life of Pi:
------------------------------
In Montreal, Canada, a writer meets Pi Patel, whom he has been told would be a good subject for a book. Pi tells the writer the following story: Pi's father names him Piscine Molitor Patel after Piscine Molitor, a famous French swimming pool. In secondary school in Pondicherry, he adopts the Greek letter "Pi" as his nickname to avoid bullying, because his first name Piscine sounds like ‘pissing’. He is raised in a Hindu family, but at 12 years old, he is introduced to Christianity and then Islam, and decides to follow all three religions as he "just wants to love God". Pi's mother supports his desire to grow, but his rationalist father tries to secularize him. Their family owns a zoo, and Pi takes interest in a Bengal tiger named Richard Parker. After he gets dangerously close to Richard Parker, his father forces him to witness it killing a goat. When Pi is 16, his father announces that due to "The Emergency", they must move to Canada, where he intends to settle and sell the animals. The family books passage with the animals on a Japanese freighter. During a storm, the ship founders while Pi is on deck. He struggles to find his family, but a crewman throws him into a lifeboat. A freed plains zebra jumps onto the boat with him, breaking its leg. The ship sinks into the Mariana Trench, drowning his family. After the storm, Pi awakens in the lifeboat with the zebra and is joined by a Bornean orangutan. A spotted hyena emerges from under a tarpaulin, forcing Pi to retreat to the end of the boat. The hyena kills the zebra and later the orangutan. Richard Parker suddenly emerges from under the tarpaulin, killing the hyena before retreating to cover. Pi fashions a small raft which he tethers to the lifeboat to be safe from Richard Parker. His moral code is against killing, but he begins fishing, enabling him to sustain the tiger. When the tiger jumps into the sea to hunt for fish and swims toward Pi, he considers letting him drown but ultimately helps him into the boat. One night, a humpback whale destroys the raft and its supplies. Pi trains Richard Parker to accept him in the boat and realizes that caring for the tiger is helping to keep himself alive. Weeks later, they encounter a floating island. It is a lush jungle of edible plants, freshwater pools and a large population of meerkats, enabling Pi and Richard Parker to eat, drink and regain strength. At night, the island transforms into a hostile environment. Richard Parker retreats to the lifeboat while Pi and the meerkats sleep in the trees; the water pools turn acidic. Pi deduces that the island is carnivorous after finding a human tooth embedded in a flower. Pi and Richard Parker leave the island, reaching Mexico after over 200 days at sea. Pi is heartbroken that Richard Parker does not acknowledge him before disappearing into the jungle. While he recovers in a hospital, insurance agents for the Japanese freighter company interview him, but do not believe his story and ask what really happened, specifically concerning why the ship sank. So Pi retells the story, in which the animals are replaced by humans: his mother for the orangutan, an amiable Buddhist sailor for the zebra, the ship's brutish cook for the hyena, and Pi himself for Richard Parker. The cook kills the sailor and feeds on his flesh. He then kills Pi's mother, after which Pi kills him and uses his remains as food and fish bait. The insurance agents are dissatisfied with this story but leave without questioning him further. When the writer recognizes the animal story may be an allegory for the human story, Pi says that it does not matter which story is true because his family died either way, and neither story provides the explanation the insurance company wanted. He asks which story the author prefers, and the author chooses the first, to which Pi replies, "and so it goes with God". Glancing at a copy of the insurance report, the writer reads that Pi survived his adventure "in the company of an adult Bengal tiger".
['United States', 'United Kingdom', 'Taiwan']
English

In [30]:
missing_counts = final_output_df.isnull().sum()
missing_percentages = final_output_df.isnull().mean() * 100
missing_summary = pd.DataFrame({
    'Missing Count': missing_counts,
    'Percentage': missing_percentages.round(2).astype(str) + '%'})

print(":סיכום ערכים חסרים בכל עמודה")
print(missing_summary)

:סיכום ערכים חסרים בכל עמודה
                 Missing Count Percentage
tconst                       0       0.0%
primaryTitle                 0       0.0%
startYear                    0       0.0%
genres                       0       0.0%
lead_actors_ids              0       0.0%
runtimeMinutes               0       0.0%
averageRating                0       0.0%
Language                  2054     41.08%
Country                   2072     41.44%
numVotes                     0       0.0%
budget                    4261     85.22%
BoxOffice                 4053     81.06%
plot                      2462     49.24%

In [31]:
final_output_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tconst           5000 non-null   object
 1   primaryTitle     5000 non-null   object
 2   startYear        5000 non-null   int64
 3   genres           5000 non-null   object
 4   lead_actors_ids  5000 non-null   object
 5   runtimeMinutes   5000 non-null   int64
 6   averageRating    5000 non-null   float64
 7   Language         2946 non-null   object
 8   Country          2928 non-null   object
 9   numVotes         5000 non-null   int64
 10  budget           739 non-null    float64
 11  BoxOffice        947 non-null    float64
 12  plot             2538 non-null   object
dtypes: float64(3), int64(3), object(7)
memory usage: 507.9+ KB

### Optional Data for part 2 or 3

#### Converting Actor IDs to Actor Names

In [32]:
df_names_try = pd.read_csv('name.basics.tsv', sep='\t',nrows=5)
df_names_try.head()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0025164"
1,nm0000002,Lauren Bacall,1924,2014,"actress,miscellaneous,soundtrack","tt0037382,tt0075213,tt0038355,tt0045891"
2,nm0000003,Brigitte Bardot,1934,2025,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"

In [33]:
df_names = pd.read_csv('name.basics.tsv', sep='\t', usecols=['nconst', 'primaryName'])
df_names.head()

      nconst      primaryName
0  nm0000001     Fred Astaire
1  nm0000002    Lauren Bacall
2  nm0000003  Brigitte Bardot
3  nm0000004     John Belushi
4  nm0000005   Ingmar Bergman

In [34]:
dataset_full = dataset_df.copy()

In [35]:
df_actors_names = top_5_actors.merge(df_names, on='nconst', how='left')
actors_names_grouped = df_actors_names.groupby('tconst')['primaryName'].apply(list).reset_index()
actors_names_grouped.rename(columns={'primaryName': 'lead_actors_names'}, inplace=True)

In [36]:
dataset_full = dataset_full.merge(actors_names_grouped, on='tconst', how='left')

In [37]:
dataset_full.head()

,tconst,primaryTitle,startYear,genres,runtimeMinutes,averageRating,numVotes,lead_actors_ids,Language,Country,budget,BoxOffice,plot,wiki_url,wiki_status,lead_actors_names
0,tt0110413,Léon: The Professional,1994,"Action,Crime,Drama",110,8.5,1348971,"[nm0000606, nm0000198, nm0000204, nm0000732, n...",English,France,16.0,19.5,"Léon is an Italian-American hitman (or ""cleane...",Local File,Cached,"[Jean Reno, Gary Oldman, Natalie Portman, Dann..."
1,tt3315342,Logan,2017,"Action,Drama,Sci-Fi",137,8.1,924570,"[nm0413168, nm0413168, nm0001772, nm6748436, n...",English,United States,112.0,619.2,"In 2029, no mutants have been born in 25 years...",Local File,Cached,"[Hugh Jackman, Hugh Jackman, Patrick Stewart, ..."
2,tt0118799,Life Is Beautiful,1997,"Comedy,Drama,Romance",116,8.6,811399,"[nm0000905, nm0000971, nm0134493, nm0243842, n...",Italian,Italy,NaN,230.1,"In 1939, in Fascist Italy, young Italian Jew G...",Local File,Cached,"[Roberto Benigni, Nicoletta Braschi, Giorgio C..."
3,tt3783958,La La Land,2016,"Comedy,Drama,Music",128,8.0,760490,"[nm0331516, nm1297015, nm1679669, nm0799777, n...",English,United States,30.0,504.6,"While stuck in Los Angeles traffic (""Another D...",Local File,Cached,"[Ryan Gosling, Emma Stone, Rosemarie DeWitt, J..."
4,tt0454876,Life of Pi,2012,"Adventure,Drama,Fantasy",127,7.9,699443,"[nm4139037, nm0451234, nm1300009, nm0007102, n...",English,"[United States, United Kingdom, Taiwan]",120.0,609.0,"In Montreal, Canada, a writer meets Pi Patel, ...",Local File,Cached,"[Suraj Sharma, Irrfan Khan, Adil Hussain, Tabu..."

In [38]:
dataset_full.drop(columns=["wiki_url", "wiki_status"], inplace=True)

In [39]:
dataset_full.columns

Index(['tconst', 'primaryTitle', 'startYear', 'genres', 'runtimeMinutes',
       'averageRating', 'numVotes', 'lead_actors_ids', 'Language', 'Country',
       'budget', 'BoxOffice', 'plot', 'lead_actors_names'],
      dtype='object')

#### Adding Directors Name

In [40]:
df_iter = pd.read_csv('title.principals.tsv', sep='\t', chunksize=500000)
director_list = []

for chunk in df_iter:
    directors = chunk[(chunk['category'] == 'director') & (chunk['tconst'].isin(dataset_full['tconst']))]
    director_list.append(directors)

In [41]:
df_directors = pd.concat(director_list)
df_directors_names = df_directors.merge(df_names, on='nconst', how='left')

In [42]:
directors_grouped = df_directors_names.groupby('tconst')['primaryName'].apply(lambda x: ", ".join(list(x))).reset_index()
directors_grouped.rename(columns={'primaryName': 'directors'}, inplace=True)

In [43]:
dataset_full.head()

,tconst,primaryTitle,startYear,genres,runtimeMinutes,averageRating,numVotes,lead_actors_ids,Language,Country,budget,BoxOffice,plot,lead_actors_names
0,tt0110413,Léon: The Professional,1994,"Action,Crime,Drama",110,8.5,1348971,"[nm0000606, nm0000198, nm0000204, nm0000732, n...",English,France,16.0,19.5,"Léon is an Italian-American hitman (or ""cleane...","[Jean Reno, Gary Oldman, Natalie Portman, Dann..."
1,tt3315342,Logan,2017,"Action,Drama,Sci-Fi",137,8.1,924570,"[nm0413168, nm0413168, nm0001772, nm6748436, n...",English,United States,112.0,619.2,"In 2029, no mutants have been born in 25 years...","[Hugh Jackman, Hugh Jackman, Patrick Stewart, ..."
2,tt0118799,Life Is Beautiful,1997,"Comedy,Drama,Romance",116,8.6,811399,"[nm0000905, nm0000971, nm0134493, nm0243842, n...",Italian,Italy,NaN,230.1,"In 1939, in Fascist Italy, young Italian Jew G...","[Roberto Benigni, Nicoletta Braschi, Giorgio C..."
3,tt3783958,La La Land,2016,"Comedy,Drama,Music",128,8.0,760490,"[nm0331516, nm1297015, nm1679669, nm0799777, n...",English,United States,30.0,504.6,"While stuck in Los Angeles traffic (""Another D...","[Ryan Gosling, Emma Stone, Rosemarie DeWitt, J..."
4,tt0454876,Life of Pi,2012,"Adventure,Drama,Fantasy",127,7.9,699443,"[nm4139037, nm0451234, nm1300009, nm0007102, n...",English,"[United States, United Kingdom, Taiwan]",120.0,609.0,"In Montreal, Canada, a writer meets Pi Patel, ...","[Suraj Sharma, Irrfan Khan, Adil Hussain, Tabu..."

In [44]:
dataset_full = dataset_full.merge(directors_grouped, on='tconst', how='left')

In [45]:
internal_columns = [
    'tconst', 'primaryTitle', 'startYear', 'genres', 
    'lead_actors_ids', 'lead_actors_names', 'directors', 
    'runtimeMinutes', 'averageRating', 'numVotes', 
    'Language', 'Country', 'budget', 'BoxOffice', 'plot'
]
dataset_full[internal_columns].to_csv('dataset_full_internal.csv', index=False)

dataset_full.head()

,tconst,primaryTitle,startYear,genres,runtimeMinutes,averageRating,numVotes,lead_actors_ids,Language,Country,budget,BoxOffice,plot,lead_actors_names,directors
0,tt0110413,Léon: The Professional,1994,"Action,Crime,Drama",110,8.5,1348971,"[nm0000606, nm0000198, nm0000204, nm0000732, n...",English,France,16.0,19.5,"Léon is an Italian-American hitman (or ""cleane...","[Jean Reno, Gary Oldman, Natalie Portman, Dann...",Luc Besson
1,tt3315342,Logan,2017,"Action,Drama,Sci-Fi",137,8.1,924570,"[nm0413168, nm0413168, nm0001772, nm6748436, n...",English,United States,112.0,619.2,"In 2029, no mutants have been born in 25 years...","[Hugh Jackman, Hugh Jackman, Patrick Stewart, ...",James Mangold
2,tt0118799,Life Is Beautiful,1997,"Comedy,Drama,Romance",116,8.6,811399,"[nm0000905, nm0000971, nm0134493, nm0243842, n...",Italian,Italy,NaN,230.1,"In 1939, in Fascist Italy, young Italian Jew G...","[Roberto Benigni, Nicoletta Braschi, Giorgio C...",Roberto Benigni
3,tt3783958,La La Land,2016,"Comedy,Drama,Music",128,8.0,760490,"[nm0331516, nm1297015, nm1679669, nm0799777, n...",English,United States,30.0,504.6,"While stuck in Los Angeles traffic (""Another D...","[Ryan Gosling, Emma Stone, Rosemarie DeWitt, J...",Damien Chazelle
4,tt0454876,Life of Pi,2012,"Adventure,Drama,Fantasy",127,7.9,699443,"[nm4139037, nm0451234, nm1300009, nm0007102, n...",English,"[United States, United Kingdom, Taiwan]",120.0,609.0,"In Montreal, Canada, a writer meets Pi Patel, ...","[Suraj Sharma, Irrfan Khan, Adil Hussain, Tabu...",Ang Lee